version: '3.8'

services:
  # Центр мониторинга
  monitoring-center:
    build: ./center
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=monitoring
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=metrics
    volumes:
      - ./logs:/app/logs
    restart: always

  # PostgreSQL для хранения конфигурации хостов
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monitoring
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    restart: always

  # MongoDB для хранения метрик
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  postgres_data:
  mongo_data:
