host_id: 12345
server_address: "http://monitoring-center:8080"
poll_interval: 60s
port: 8081
processes:
  - "nginx"
  - "postgres"
  - "redis"
containers:
  - "build-mongodb-1"
  - "build-postgres-1"
