server:
  port: "8080"
  read_timeout: 30s
  write_timeout: 30s

postgres:
  host: "build-postgres-1"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "monitoring"
  sslmode: "disable"
  driver: "postgres"
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: 5m

mongodb:
  uri: "mongodb://mongodb:27017"
  dbname: "metrics"
  connectTimeout: 5s
  maxPoolSize: 20
  minPoolSize: 5
  serverSelectionTimeout: 10s

metrics:
  poll_interval: 60s
  metrics_ttl_days: 14
  self_check_interval: 5m

  system:
    enabled: true
    collect_cpu: true
    collect_ram: true
    collect_disks: true

  process:
    enabled: true

  network:
    enabled: true
    monitor_tcp: true
    monitor_udp: true

  container:
    enabled: true

logging:
  level: "info"
  file_path: "/app/logs/monitoring.log"
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

alerts:
  telegram:
    token: "7490774913:AAG1xgAyR63-jEdmSIYE8-h__1yS1QyXuno"
    chat_ids:
      - "1139325406"
      - "-1002496179321"

  email:
    to:
      - "a1@gmail.com"
      - "a2@gmail.com"
    smtp_host: "smtp.gmail.com"
    smtp_port: 465
    username: "a@gmail.com"
    password: "45"

  failure_threshold_percent: 90
  interval_seconds: 60

initial_data:
  hosts:
    - hostname: "12345"
      ip_address: 192.168.58.129
      agent_port: 8081
      priority: 10
      is_master: true
      status: "active"
      processes:
        - "nginx"
        - "postgres"
        - "redis"
      containers:
        - "build-mongodb-1"
        - "build-postgres-1"
        - "build-mongodb-1"
      alerts:
        # Системные метрики
        - metric_name: "system.cpu_usage_percent"
          threshold_value: 1.0
          condition: ">"
          enabled: true
        - metric_name: "system.memory_usage_percent"
          threshold_value: 1.0
          condition: ">"
          enabled: true
        - metric_name: "system.cpu_usage_percent"
          threshold_value: 1.0
          condition: "<"
          enabled: true

        # Метрики процессов
        - metric_name: "process.postgres.cpu_percent"
          threshold_value: 1.0
          condition: ">"
          enabled: true

        # Метрики контейнеров
        - metric_name: "container.build-mongodb-1.status"
          threshold_value: 1 # 1 = running, 0 = stopped
          condition: "="
          enabled: true
        - metric_name: "container.build-mongodb-1.cpu_percent"
          threshold_value: 1.0
          condition: ">"
          enabled: true

        # Сетевые метрики
        - metric_name: "network.80.status"
          threshold_value: 1 # 1 = LISTEN, 0 = other
          condition: "="
          enabled: true
#    - hostname: "server-2"
#      ip_address: 192.168.58.128
#      agent_port: 8081
#      priority: 5
#      is_master: false
#      processes:
#        - "nginx"
#        - "postgres"
#        - "redis"
#      containers:
#        - "build-mongodb-1"
#        - "build-postgres-1"
