basePath: /
definitions:
  models.AgentMetrics:
    properties:
      containers:
        items:
          $ref: '#/definitions/models.ContainerInfo'
        type: array
      host_id:
        type: string
      ports:
        items:
          $ref: '#/definitions/models.PortInfo'
        type: array
      processes:
        items:
          $ref: '#/definitions/models.ProcessInfo'
        type: array
      system:
        $ref: '#/definitions/models.SystemMetrics'
      timestamp:
        type: string
    type: object
  models.CPUMetrics:
    properties:
      usage_percent:
        description: Процент использования CPU
        type: number
    type: object
  models.ContainerInfo:
    properties:
      cpu_percent:
        description: Процент использования CPU
        type: number
      id:
        description: Короткий ID контейнера
        type: string
      image:
        description: Образ контейнера
        type: string
      mem_percent:
        description: Процент использования памяти
        type: number
      name:
        description: Имя контейнера
        type: string
      status:
        description: Статус (running, stopped, etc.)
        type: string
    type: object
  models.DiskMetrics:
    properties:
      free:
        description: Свободный объем в байтах
        type: integer
      total:
        description: Общий объем в байтах
        type: integer
      usage_percent:
        description: Процент использования
        type: number
      used:
        description: Используемый объем в байтах
        type: integer
    type: object
  models.PortInfo:
    properties:
      port:
        description: Номер порта
        type: integer
      protocol:
        description: Протокол (TCP/UDP)
        type: string
      state:
        description: Состояние (LISTEN, etc.)
        type: string
    type: object
  models.ProcessInfo:
    properties:
      cpu_percent:
        description: Процент использования CPU
        type: number
      mem_percent:
        description: Процент использования памяти
        type: number
      name:
        description: Имя процесса
        type: string
      pid:
        description: ID процесса
        type: integer
    type: object
  models.RAMMetrics:
    properties:
      free:
        description: Свободный объем в байтах
        type: integer
      total:
        description: Общий объем в байтах
        type: integer
      usage_percent:
        description: Процент использования
        type: number
      used:
        description: Используемый объем в байтах
        type: integer
    type: object
  models.SystemMetrics:
    properties:
      cpu:
        $ref: '#/definitions/models.CPUMetrics'
      disk:
        $ref: '#/definitions/models.DiskMetrics'
      ram:
        $ref: '#/definitions/models.RAMMetrics'
    type: object
host: localhost:8080
info:
  contact: {}
  description: API сервиса мониторинга
  title: Agent API
  version: "1.0"
paths:
  /api/config/collection-interval:
    post:
      consumes:
      - application/json
      description: Изменяет временной интервал между сборами метрик агента
      parameters:
      - description: Интервал сбора в секундах (положительное число)
        in: body
        name: request
        required: true
        schema:
          properties:
            interval_seconds:
              type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Интервал успешно обновлен
          schema:
            properties:
              interval_seconds:
                type: integer
              message:
                type: string
              status:
                type: string
            type: object
        "400":
          description: Некорректные входные данные
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      summary: Обновление интервала сбора метрик
      tags:
      - configuration
  /api/config/containers:
    post:
      consumes:
      - application/json
      description: Устанавливает список Docker контейнеров, метрики которых будут
        собираться
      parameters:
      - description: Массив имён контейнеров для отслеживания
        in: body
        name: request
        required: true
        schema:
          properties:
            containers:
              type: array
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Конфигурация успешно обновлена
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "400":
          description: Некорректный формат данных или пустой список
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      summary: Обновление списка отслеживаемых контейнеров
      tags:
      - configuration
  /api/config/processes:
    post:
      consumes:
      - application/json
      description: Устанавливает список процессов, метрики которых будут собираться
      parameters:
      - description: Массив имён процессов для отслеживания
        in: body
        name: request
        required: true
        schema:
          properties:
            processes:
              type: array
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Конфигурация успешно обновлена
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "400":
          description: Некорректный формат данных или пустой список
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      summary: Обновление списка отслеживаемых процессов
      tags:
      - configuration
  /api/health:
    get:
      description: Проверяет работоспособность агента и возвращает статус
      produces:
      - application/json
      responses:
        "200":
          description: Агент работает
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      summary: Проверка работоспособности
      tags:
      - system
  /api/metrics:
    get:
      description: Возвращает все собранные метрики агента
      produces:
      - application/json
      responses:
        "200":
          description: Все метрики
          schema:
            $ref: '#/definitions/models.AgentMetrics'
      summary: Получение всех метрик
      tags:
      - metrics
  /api/metrics/containers:
    get:
      description: Возвращает метрики отслеживаемых Docker контейнеров
      produces:
      - application/json
      responses:
        "200":
          description: Метрики контейнеров
          schema:
            properties:
              containers:
                type: array
              host_id:
                type: string
              timestamp:
                type: string
            type: object
        "400":
          description: Список отслеживаемых контейнеров не настроен
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      summary: Получение метрик контейнеров
      tags:
      - metrics
  /api/metrics/network:
    get:
      description: Возвращает информацию о сетевых соединениях и открытых портах
      produces:
      - application/json
      responses:
        "200":
          description: Сетевые метрики
          schema:
            properties:
              host_id:
                type: string
              ports:
                type: array
              timestamp:
                type: string
            type: object
      summary: Получение сетевых метрик
      tags:
      - metrics
  /api/metrics/processes:
    get:
      description: Возвращает метрики отслеживаемых процессов
      produces:
      - application/json
      responses:
        "200":
          description: Метрики процессов
          schema:
            properties:
              host_id:
                type: string
              processes:
                type: array
              timestamp:
                type: string
            type: object
        "400":
          description: Список отслеживаемых процессов не настроен
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      summary: Получение метрик процессов
      tags:
      - metrics
  /api/metrics/system:
    get:
      description: Возвращает только системные метрики агента
      produces:
      - application/json
      responses:
        "200":
          description: Системные метрики
          schema:
            properties:
              host_id:
                type: string
              system:
                type: object
              timestamp:
                type: string
            type: object
      summary: Получение системных метрик
      tags:
      - metrics
swagger: "2.0"
