// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Проверяет работоспособность сервиса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Проверка состояния системы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts": {
            "get": {
                "description": "Возвращает список всех зарегистрированных хостов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Получить список всех хостов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Host"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет новый хост в систему",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Создать новый хост",
                "parameters": [
                    {
                        "description": "Данные хоста",
                        "name": "host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HostInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID созданного хоста",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/master": {
            "get": {
                "description": "Возвращает информацию о текущем мастер-хосте",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Получить мастер-хост",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Host"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}": {
            "get": {
                "description": "Возвращает информацию о хосте по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Получить хост по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Host"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет информацию о существующем хосте",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Обновить данные хоста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные хоста",
                        "name": "host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HostInput"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет хост из системы по ID",
                "tags": [
                    "Hosts"
                ],
                "summary": "Удалить хост",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/alerts": {
            "get": {
                "description": "Возвращает все правила оповещений для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Получить правила оповещений для хоста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AlertRule"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новое правило оповещения для указанного хоста",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Создать правило оповещения",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные правила оповещения",
                        "name": "alert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AlertInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID созданного правила",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/alerts/{alert_id}": {
            "put": {
                "description": "Обновляет существующее правило оповещения",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Обновить правило оповещения",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID правила оповещения",
                        "name": "alert_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные правила",
                        "name": "alert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AlertInput"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет правило оповещения по ID",
                "tags": [
                    "Alerts"
                ],
                "summary": "Удалить правило оповещения",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID правила оповещения",
                        "name": "alert_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/alerts/{alert_id}/status": {
            "patch": {
                "description": "Изменяет статус активности правила оповещения",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Включить/выключить правило оповещения",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID правила оповещения",
                        "name": "alert_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Статус активности",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/containers": {
            "get": {
                "description": "Возвращает все контейнеры для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Containers"
                ],
                "summary": "Получить контейнеры для хоста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Container"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет новый контейнер для мониторинга на указанном хосте",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Containers"
                ],
                "summary": "Добавить контейнер для мониторинга",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные контейнера",
                        "name": "container",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID созданного контейнера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/containers/{container_id}": {
            "delete": {
                "description": "Удаляет контейнер из списка мониторинга",
                "tags": [
                    "Containers"
                ],
                "summary": "Удалить контейнер из мониторинга",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контейнера",
                        "name": "container_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/master": {
            "put": {
                "description": "Назначает указанный хост мастер-хостом",
                "tags": [
                    "Hosts"
                ],
                "summary": "Установить мастер-хост",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/processes": {
            "get": {
                "description": "Возвращает все процессы для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processes"
                ],
                "summary": "Получить процессы для хоста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Process"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет новый процесс для мониторинга на указанном хосте",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processes"
                ],
                "summary": "Добавить процесс для мониторинга",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные процесса",
                        "name": "process",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProcessInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID созданного процесса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/{id}/processes/{process_id}": {
            "delete": {
                "description": "Удаляет процесс из списка мониторинга",
                "tags": [
                    "Processes"
                ],
                "summary": "Удалить процесс из мониторинга",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID процесса",
                        "name": "process_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Возвращает агрегированные метрики по всем хостам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Получить все метрики",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Принимает и сохраняет метрики, отправленные агентом",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Принять метрики от агента",
                "parameters": [
                    {
                        "description": "Метрика",
                        "name": "metrics",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HostMetricsResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{host_id}": {
            "get": {
                "description": "Возвращает все метрики для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Получить метрики для хоста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "host_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{host_id}/containers": {
            "get": {
                "description": "Возвращает метрики контейнеров для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Получить метрики контейнеров",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "host_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2023-01-01T00:00:00Z\"",
                        "description": "Начало периода (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2023-01-02T23:59:59Z\"",
                        "description": "Конец периода (RFC3339)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ContainerMetrics"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{host_id}/network": {
            "get": {
                "description": "Возвращает сетевые метрики для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Получить сетевые метрики",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "host_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2023-01-01T00:00:00Z\"",
                        "description": "Начало периода (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2023-01-02T23:59:59Z\"",
                        "description": "Конец периода (RFC3339)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.NetworkMetrics"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{host_id}/processes": {
            "get": {
                "description": "Возвращает метрики процессов для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Получить метрики процессов",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "host_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2023-01-01T00:00:00Z\"",
                        "description": "Начало периода (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2023-01-02T23:59:59Z\"",
                        "description": "Конец периода (RFC3339)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ProcessMetrics"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{host_id}/system": {
            "get": {
                "description": "Возвращает системные метрики для указанного хоста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Получить системные метрики",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хоста",
                        "name": "host_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SystemMetrics"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AlertInput": {
            "type": "object",
            "required": [
                "condition",
                "metric_name",
                "threshold_value"
            ],
            "properties": {
                "condition": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "metric_name": {
                    "type": "string"
                },
                "threshold_value": {
                    "type": "number"
                }
            }
        },
        "models.AlertRule": {
            "type": "object",
            "required": [
                "condition",
                "metric_name",
                "threshold_value"
            ],
            "properties": {
                "condition": {
                    "description": "\"greater\", \"less\", \"equal\"",
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "metric_name": {
                    "type": "string"
                },
                "threshold_value": {
                    "type": "number"
                }
            }
        },
        "models.CPUInfo": {
            "type": "object",
            "properties": {
                "usage_percent": {
                    "type": "number"
                }
            }
        },
        "models.Container": {
            "type": "object",
            "required": [
                "container_name"
            ],
            "properties": {
                "container_name": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.ContainerInfo": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "mem_percent": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.ContainerInput": {
            "type": "object",
            "required": [
                "container_name"
            ],
            "properties": {
                "container_name": {
                    "type": "string"
                }
            }
        },
        "models.ContainerMetrics": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ContainerInfo"
                    }
                },
                "host_id": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.DiskInfo": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "models.Host": {
            "type": "object",
            "required": [
                "hostname",
                "ip_address"
            ],
            "properties": {
                "agent_port": {
                    "type": "integer"
                },
                "created_at": {
                    "description": "LastCheck time.Time ` + "`" + `json:\"last_check\" db:\"last_check\"` + "`" + `",
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_master": {
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.HostInput": {
            "type": "object",
            "required": [
                "agent_port",
                "hostname",
                "ip_address"
            ],
            "properties": {
                "agent_port": {
                    "type": "integer"
                },
                "hostname": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                }
            }
        },
        "models.HostMetricsResponse": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ContainerMetrics"
                    }
                },
                "network": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NetworkMetrics"
                    }
                },
                "processes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessMetrics"
                    }
                },
                "system": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SystemMetrics"
                    }
                }
            }
        },
        "models.NetworkMetrics": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "integer"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PortInfo"
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.PortInfo": {
            "type": "object",
            "properties": {
                "local_port": {
                    "type": "integer"
                },
                "process": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "models.Process": {
            "type": "object",
            "required": [
                "process_name"
            ],
            "properties": {
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "process_name": {
                    "type": "string"
                }
            }
        },
        "models.ProcessInfo": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "Status     string  ` + "`" + `json:\"status\" bson:\"status\"` + "`" + `",
                    "type": "number"
                },
                "memory_mb": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                }
            }
        },
        "models.ProcessInput": {
            "type": "object",
            "required": [
                "process_name"
            ],
            "properties": {
                "process_name": {
                    "type": "string"
                }
            }
        },
        "models.ProcessMetrics": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "integer"
                },
                "processes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessInfo"
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.RAMInfo": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "models.SystemDetails": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/models.CPUInfo"
                },
                "disk": {
                    "$ref": "#/definitions/models.DiskInfo"
                },
                "ram": {
                    "$ref": "#/definitions/models.RAMInfo"
                }
            }
        },
        "models.SystemMetrics": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "integer"
                },
                "system": {
                    "$ref": "#/definitions/models.SystemDetails"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Center API",
	Description:      "API сервиса мониторинга",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
